### ISSUE TITLE
Is GraphQL the way forward for Solidus?

### ISSUE THREAD

**Issue by incorvia** [solidusio-contrib/solidus_graphql_api#160]
I'm evaluating Solidus. It appears looking back at posts a year ago that GraphQL was being pitched as the future for Solidus. It's now been 8 months since a release.. does that mean that this gem is really stable? Is GraphQL being abandoned as the future of Solidus? Trying to figure out how I would develop my application and whether it's better to build on the rest API or on GraphQL

**Comment by jarednorman** [comment]
For the team being the existing API isn't going anywhere, but the GraphQL extension remains as an opt-in option for those that prefer the technology. I'm personally not running any stores that are using it, though we have experimented with it, so I'll let someone whose got more knowledge here speak to stability and completeness.
