### ISSUE TITLE
How to add new query

### ISSUE THREAD

**Issue by rocalex** [solidusio-contrib/solidus_graphql_api#168]
I want to add a variable to taxonomies, for example, slug.
The query I expect is
```
query {
  taxonomiesByName(name: "Preset") {
    nodes {
      name
      taxons {
        nodes {
          name
          permalink
        }
      }
    }
  }
}
```
I added query_decorators.rb into app/graphql/types directory

```
# frozen_string_literal: true

module Graphql
  module Types
    module QueryDecorator
      def self.prepended(base)
        base.field :taxonomies_by_name, SolidusGraphqlApi::Types::Taxonomy.connection_type, null: false, description: 'Supported taxonomies by name' do
          argument :name, String, required: true
        end
      end

      def taxonomies_by_name(name:)
        Spree::Taxonomy.find_by(name: name)
      end

      SolidusGraphqlApi::Types::Query.prepend self
    end
  end
end
```

When I call this query, I got an error.

```
{
  "error": {
    "message": "No connection implementation to wrap Spree::Taxonomy (#<Spree::Taxonomy:0x00007fb2c7d7e020>)",
    "backtrace": [
...
```
How to fix it?

**Comment by kennyadsl** [comment]
I think it should be `SolidusGraphqlApi::Types::Query::Taxonomy` instead of `SolidusGraphqlApi::Types::Taxonomy`, even if I'm not sure the error you get is related. Let me know!

**Comment by kennyadsl** [comment]
Hey @rocalex, I didn't find the time to get back to this issue. Did you ever manage to solve it?

**Comment by rocalex** [comment]
> Hey @rocalex, I didn't find the time to get back to this issue. Did you ever manage to solve it?

Not yet.

**Comment by ChristianRimondi** [comment]
hey @rocalex, here:
```ruby
def taxonomies_by_name(name:)
  Spree::Taxonomy.find_by(name: name)
end 
```
you are using a `find_by` which returns a single record. Try with `Spree::Taxonomy.where(name: name)`

**Comment by kennyadsl** [comment]
I think we can close this one. Thanks @ChristianRimondi for answering!
