### ISSUE TITLE
No support for Ruby 3 & status of the gem

### ISSUE THREAD

**Issue by brettchalupa** [solidusio-contrib/solidus_graphql_api#206]
Hi there! I'm hoping to use this gem in a Solidus 3.4 app to add some additional API functionality. I'm really interested in evaluating it and using it, but it hasn't received any updates in 1.5 years. When I try to `bundle` in a Ruby 3.1 app, I get this error:

```
solidus_graphql_api was resolved to 0.2.0, which depends on
  Ruby (~> 2.5)
```

Is this gem actively maintained? If so, will you all accept patches to update the gem to support Ruby 3.x and some modern versions of the GQL dependencies? Happy to help contribute, but I just want to ensure it's welcomed effort.

Thanks!

**Comment by kennyadsl** [comment]
Hey @brettchalupa, this gem is not actively maintained but we would consider merging any PR which could improve the current state of it. There's already something at https://github.com/solidusio-contrib/solidus_graphql_api/pull/204, which it's still draft but could be a good starting point. 

If you want to contribute, you can definitely count on me for guidance.

**Comment by brettchalupa** [comment]
@kennyadsl sounds good! Thanks for the details. :+1: I got the gem working on Ruby 3, Rails 7, Solidus 3.x on a fork of the repo. I'll work on contributing that back upstream.
